### PR TITLE
Close popup when user clicks on a link

### LINKED ISSUE #16: tracker report cannot be dismissed on SERP
steps to reproduce (iphone 13 pro, 15.3.1):

1. Search for smth
2. Open a tracker report on SERP
3. Don’t close
4. Scroll to another result and navigate to website
5. Come back to SERP
6. Open tracker report remained opened and the close icon is not responding

### PR DESCRIPTION
**Pull request by smalluban**
Fixes #16.

### CODE REVIEW

File: packages/serp-report/src/content_scripts/serp-report.js [hunk 1]
```diff
@@ -95,84 +97,98 @@ function removeWheel(anchor) {
...
   ];
 
-  const links = elements.map((el) => {
-    if (el.hostname === window.location.hostname) {
-      const url = new URL(el.href);
-      return url.searchParams.get('url') || url.searchParams.get('q');
-    }
-    return el.href;
-  });
+  if (elements.length) {
```
Comment (smalluban) [inline packages/serp-report/src/content_scripts/serp-report.js:106]: Added condition.

**Review by philipp-classen — APPROVED** [review]

**Review by chrmod — COMMENTED** [review]
is it possible to implement the change without changing the indentation? now the diff is very hard to read.

**Comment by philipp-classen** [comment]
> is it possible to implement the change without changing the indentation? now the diff is very hard to read.

Hiding white spaces in Github helps.

**Review by chrmod — APPROVED** [review]
